UPDATE Pokemon SET STAGE='Special Stage' WHERE POKEMON_ID='474';
UPDATE Pokemon SET SKILL='Rock Break+' WHERE POKEMON_ID='474';
UPDATE Pokemon SET BASE_POWER=60 WHERE POKEMON_ID='474';
UPDATE Pokemon SET CAPTURE_RATE='9%' WHERE POKEMON_ID='474';
UPDATE Pokemon SET STAGE='Special Stage' WHERE POKEMON_ID='476';
UPDATE Pokemon SET SKILL='Barrier Bash+' WHERE POKEMON_ID='476';
UPDATE Pokemon SET BASE_POWER=60 WHERE POKEMON_ID='476';
UPDATE Pokemon SET CAPTURE_RATE='9%' WHERE POKEMON_ID='476';
UPDATE Pokemon SET SKILL='Latios Mega Power' Where NAME='Mega Latios'
UPDATE Pokemon SET ELEMENT='type_rock' WHERE POKEMON_ID='452';
UPDATE Pokemon SET ELEMENT='type_rock' WHERE POKEMON_ID='453';