UPDATE Pokemon SET NAME='Wartortle' WHERE POKEMON_ID='8';
UPDATE Pokemon SET NAME='Sawk' WHERE POKEMON_ID='142';
UPDATE Pokemon SET SKILL='Block Smash' WHERE POKEMON_ID='425';
UPDATE Pokemon SET SKILL='Eject+' WHERE POKEMON_ID='290';